# Generated by Django 3.2.9 on 2021-11-24 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[(1, 'New'), (2, 'Used'), (3, 'Damaged')], default=1, max_length=30)),
                ('section', models.IntegerField()),
                ('loaned', models.BooleanField(default=False)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.library')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('series', models.CharField(max_length=50)),
                ('synopsis', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=20, unique=True)),
                ('date_of_publication', models.DateTimeField()),
                ('publisher', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('pages', models.IntegerField()),
                ('tags', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PublicationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('price', models.FloatField()),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api_app.publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_books', models.IntegerField()),
                ('price_per_book', models.FloatField()),
                ('publication_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.publicationorder')),
            ],
        ),
        migrations.CreateModel(
            name='BookLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('extension_to', models.DateTimeField()),
                ('fine', models.FloatField(default=0)),
                ('books', models.ManyToManyField(to='api_app.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.publication'),
        ),
    ]
