# Generated by Django 3.2.9 on 2021-11-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='library',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
