# Generated by Django 3.2.9 on 2021-11-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20211124_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='availiable_at',
            field=models.ManyToManyField(to='api_app.Library'),
        ),
    ]
